CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  RETURN (
      select DISTINCT SALARY FROM (SELECT SALARY ,DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RNK FROM EMPLOYEE)AS T WHERE RNK=N
  );
END